"""Generate the full UAF + SysML + BPMN T-Box from the seeded :Stereotype metamodel.

Reads the :Stereotype / :Domain nodes seeded by
cypher/init_uaf_graph.cypher (which mirror UAFStereotypeRegistry)
and the REL_* constants in UAFRelationshipDTO.java. Emits ontology/uaf-mvo.ttl
covering all three modelling languages (no domain filter).

The companion ontology/n10s-mappings.cypher file was dropped along with the
n10s integration (see ontology/NEXT-STEPS.md decision log 2026-05-19). If n10s
is ever reintroduced as a third RDF surface, regenerate from the same
:Stereotype data via a separate codegen path.

Per-language conventions:
- UAF stereotypes  -> uaf:    namespace, subClassOf the abstract UAF domain superclass
- SysML stereotypes -> sysml: namespace, subClassOf sysml:SysMLElement
- BPMN stereotypes  -> bpmn:  namespace, subClassOf bpmn:BPMNElement

Object properties (relationship types) live in the uaf: namespace because they
are shared across languages by the Java plugin.

Usage:
    python ontology/codegen/generate_mvo.py
"""

from __future__ import annotations

import os
import re
import sys
from datetime import date
from pathlib import Path

from neo4j import GraphDatabase

REPO_ROOT = Path(__file__).resolve().parents[2]
RELATIONSHIP_DTO = (
    REPO_ROOT
    / "msosa-model-exporter"
    / "src"
    / "main"
    / "java"
    / "com"
    / "uaf"
    / "neo4j"
    / "plugin"
    / "model"
    / "UAFRelationshipDTO.java"
)
OUT_DIR = REPO_ROOT / "ontology"
TTL_OUT = OUT_DIR / "uaf-mvo.ttl"

UAF_NS = "http://msosa-toolbox.local/uaf#"
UAF_PROP_NS = "http://msosa-toolbox.local/uaf/prop#"
SYSML_NS = "http://msosa-toolbox.local/sysml#"
BPMN_NS = "http://msosa-toolbox.local/bpmn#"
ONTOLOGY_IRI = "http://msosa-toolbox.local/uaf/mvo"

# UAF domain → abstract superclass for that domain (in uaf: namespace).
UAF_DOMAIN_SUPERCLASS = {
    "STRATEGIC":   "StrategicElement",
    "OPERATIONAL": "OperationalElement",
    "RESOURCE":    "ResourceElement",
    "SERVICE":     "ServiceElement",
    "PERSONNEL":   "PersonnelElement",
    "ACQUISITION": "AcquisitionElement",
    "SECURITY":    "SecurityElement",
    "SHARED":      "SharedElement",
}

# Language-level superclass per non-UAF language.
LANG_SUPERCLASS = {
    "SysML": ("sysml", "SysMLElement"),
    "BPMN":  ("bpmn",  "BPMNElement"),
}

REL_CONSTANT_RE = re.compile(
    r'public\s+static\s+final\s+String\s+REL_[A-Z_]+\s*=\s*"([A-Z_]+)"\s*;'
)


def fetch_stereotypes(uri: str, user: str, password: str, database: str) -> list[dict]:
    driver = GraphDatabase.driver(uri, auth=(user, password))
    try:
        with driver.session(database=database) as session:
            result = session.run(
                """
                MATCH (s:Stereotype)
                RETURN s.name AS name,
                       s.domain AS domain,
                       coalesce(s.language, 'UAF') AS language
                ORDER BY language, coalesce(domain, ''), name
                """
            )
            return [r.data() for r in result]
    finally:
        driver.close()


def parse_relationship_constants(java_file: Path) -> list[str]:
    text = java_file.read_text(encoding="utf-8")
    seen: list[str] = []
    for match in REL_CONSTANT_RE.finditer(text):
        value = match.group(1)
        if value not in seen:
            seen.append(value)
    return seen


def to_property_iri(rel_type: str) -> str:
    head, *tail = rel_type.lower().split("_")
    return head + "".join(p.capitalize() for p in tail)


def render_turtle(stereotypes: list[dict], rel_types: list[str]) -> str:
    today = date.today().isoformat()

    by_lang: dict[str, list[dict]] = {"UAF": [], "SysML": [], "BPMN": []}
    for row in stereotypes:
        lang = row["language"]
        if lang in by_lang:
            by_lang[lang].append(row)

    lines: list[str] = []
    lines.append("# UAF + SysML + BPMN Minimum Viable Ontology (MVO)")
    lines.append("# Covers all UAF 1.2 domains plus SysML 1.6 and BPMN 2.0 stereotypes.")
    lines.append("# AUTO-GENERATED by ontology/codegen/generate_mvo.py — do not hand-edit.")
    lines.append("# Source of truth: UAFStereotypeRegistry.java (mirrored into Neo4j by init_uaf_graph.cypher)")
    lines.append("")
    lines.append("@prefix owl:     <http://www.w3.org/2002/07/owl#> .")
    lines.append("@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .")
    lines.append("@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .")
    lines.append("@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .")
    lines.append("@prefix dcterms: <http://purl.org/dc/terms/> .")
    lines.append(f"@prefix uaf:     <{UAF_NS}> .")
    lines.append(f"@prefix uafprop: <{UAF_PROP_NS}> .")
    lines.append(f"@prefix sysml:   <{SYSML_NS}> .")
    lines.append(f"@prefix bpmn:    <{BPMN_NS}> .")
    lines.append("")
    lines.append(f"<{ONTOLOGY_IRI}> a owl:Ontology ;")
    lines.append('    rdfs:label "UAF + SysML + BPMN MVO" ;')
    lines.append('    rdfs:comment "Minimum Viable Ontology covering UAF 1.2 (all 8 domains), SysML 1.6 and BPMN 2.0 stereotypes, generated from UAFStereotypeRegistry." ;')
    lines.append('    owl:versionInfo "0.2.0" ;')
    lines.append(f'    dcterms:created "{today}"^^xsd:date .')
    lines.append("")

    # Annotation properties
    lines.append("# --- Annotation properties ---------------------------------------------------")
    lines.append("")
    lines.append("uafprop:domain a owl:AnnotationProperty ;")
    lines.append('    rdfs:label "uaf domain" .')
    lines.append("")
    lines.append("uafprop:language a owl:AnnotationProperty ;")
    lines.append('    rdfs:label "source modelling language" .')
    lines.append("")
    lines.append("uafprop:neo4jType a owl:AnnotationProperty ;")
    lines.append('    rdfs:label "neo4j relationship type" .')
    lines.append("")

    # UAF domain superclasses
    lines.append("# --- UAF domain superclasses -------------------------------------------------")
    lines.append("")
    for domain, super_name in UAF_DOMAIN_SUPERCLASS.items():
        lines.append(f"uaf:{super_name} a owl:Class ;")
        lines.append(f'    rdfs:label "{super_name}" ;')
        lines.append(f'    rdfs:comment "Abstract superclass for UAF {domain.lower()} domain elements." ;')
        lines.append(f'    uafprop:domain "{domain}" ;')
        lines.append('    uafprop:language "UAF" .')
        lines.append("")

    # SysML / BPMN language-level superclasses
    lines.append("# --- Language-level superclasses ---------------------------------------------")
    lines.append("")
    for lang, (prefix, super_name) in LANG_SUPERCLASS.items():
        lines.append(f"{prefix}:{super_name} a owl:Class ;")
        lines.append(f'    rdfs:label "{super_name}" ;')
        lines.append(f'    rdfs:comment "Abstract superclass for {lang} elements." ;')
        lines.append(f'    uafprop:language "{lang}" .')
        lines.append("")

    # UAF concrete classes per domain
    lines.append("# --- UAF concrete classes ----------------------------------------------------")
    lines.append("")
    for domain in UAF_DOMAIN_SUPERCLASS:
        rows = [r for r in by_lang["UAF"] if r["domain"] == domain]
        if not rows:
            continue
        super_name = UAF_DOMAIN_SUPERCLASS[domain]
        lines.append(f"# UAF {domain}")
        for row in rows:
            name = row["name"]
            lines.append(f"uaf:{name} a owl:Class ;")
            lines.append(f'    rdfs:label "{name}" ;')
            lines.append(f"    rdfs:subClassOf uaf:{super_name} ;")
            lines.append(f'    uafprop:domain "{domain}" ;')
            lines.append('    uafprop:language "UAF" ;')
            lines.append(f"    rdfs:isDefinedBy <{ONTOLOGY_IRI}> .")
            lines.append("")

    # SysML / BPMN concrete classes
    for lang in ("SysML", "BPMN"):
        rows = by_lang[lang]
        if not rows:
            continue
        prefix, super_name = LANG_SUPERCLASS[lang]
        lines.append(f"# --- {lang} concrete classes -------------------------------------------------")
        lines.append("")
        for row in rows:
            name = row["name"]
            lines.append(f"{prefix}:{name} a owl:Class ;")
            lines.append(f'    rdfs:label "{name}" ;')
            lines.append(f"    rdfs:subClassOf {prefix}:{super_name} ;")
            lines.append(f'    uafprop:language "{lang}" ;')
            lines.append(f"    rdfs:isDefinedBy <{ONTOLOGY_IRI}> .")
            lines.append("")

    # Object properties (shared across all languages)
    lines.append("# --- Object properties (UAF relationship types) ------------------------------")
    lines.append("")
    for rel in rel_types:
        prop_iri = to_property_iri(rel)
        lines.append(f"uaf:{prop_iri} a owl:ObjectProperty ;")
        lines.append(f'    rdfs:label "{rel}" ;')
        lines.append(f'    uafprop:neo4jType "{rel}" ;')
        lines.append(f"    rdfs:isDefinedBy <{ONTOLOGY_IRI}> .")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    uri = os.getenv("NEO4J_URI", "bolt://localhost:7687")
    user = os.getenv("NEO4J_USERNAME", "neo4j")
    password = os.getenv("NEO4J_PASSWORD", "Password123")
    database = os.getenv("NEO4J_DATABASE", "neo4j")

    print(f"Querying {uri} for all stereotypes...", file=sys.stderr)
    stereotypes = fetch_stereotypes(uri, user, password, database)
    if not stereotypes:
        print("ERROR: no :Stereotype nodes found. Run init_uaf_graph.cypher first.",
              file=sys.stderr)
        return 1

    rel_types = parse_relationship_constants(RELATIONSHIP_DTO)
    if not rel_types:
        print("ERROR: no REL_* constants parsed from UAFRelationshipDTO.java",
              file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TTL_OUT.write_text(render_turtle(stereotypes, rel_types), encoding="utf-8")

    by_lang: dict[str, int] = {}
    for r in stereotypes:
        by_lang[r["language"]] = by_lang.get(r["language"], 0) + 1
    summary = ", ".join(f"{lang}={n}" for lang, n in sorted(by_lang.items()))
    print(f"Wrote {TTL_OUT.relative_to(REPO_ROOT)} "
          f"({len(stereotypes)} classes [{summary}], {len(rel_types)} object properties)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
