"""Generate the UAF Minimum Viable Ontology (MVO) Turtle file from the metamodel.

Reads the :Stereotype/:Domain nodes seeded by
uaf-neo4j-plugin/cypher/init_uaf_graph.cypher (which mirror UAFStereotypeRegistry)
and the REL_* constants in UAFRelationshipDTO.java. Emits ontology/uaf-mvo.ttl
and ontology/n10s-mappings.cypher.

Scope: Strategic + Operational + Resource UAF stereotypes (Stage 2 MVO).
The registry remains the single source of truth; regenerate after any change.

Usage:
    python ontology/codegen/generate_mvo.py
"""

from __future__ import annotations

import os
import re
import sys
from datetime import date
from pathlib import Path

from neo4j import GraphDatabase

REPO_ROOT = Path(__file__).resolve().parents[2]
RELATIONSHIP_DTO = (
    REPO_ROOT
    / "uaf-neo4j-plugin"
    / "src"
    / "main"
    / "java"
    / "com"
    / "uaf"
    / "neo4j"
    / "plugin"
    / "model"
    / "UAFRelationshipDTO.java"
)
OUT_DIR = REPO_ROOT / "ontology"
TTL_OUT = OUT_DIR / "uaf-mvo.ttl"
MAPPINGS_OUT = OUT_DIR / "n10s-mappings.cypher"

UAF_NS = "http://msosa-toolbox.local/uaf#"
UAF_PROP_NS = "http://msosa-toolbox.local/uaf/prop#"
ONTOLOGY_IRI = "http://msosa-toolbox.local/uaf/mvo"

IN_SCOPE_DOMAINS = ("STRATEGIC", "OPERATIONAL", "RESOURCE")
DOMAIN_TO_SUPERCLASS = {
    "STRATEGIC": "StrategicElement",
    "OPERATIONAL": "OperationalElement",
    "RESOURCE": "ResourceElement",
}

REL_CONSTANT_RE = re.compile(
    r'public\s+static\s+final\s+String\s+REL_[A-Z_]+\s*=\s*"([A-Z_]+)"\s*;'
)


def fetch_stereotypes(uri: str, user: str, password: str, database: str) -> list[dict]:
    driver = GraphDatabase.driver(uri, auth=(user, password))
    try:
        with driver.session(database=database) as session:
            result = session.run(
                """
                MATCH (s:Stereotype)
                WHERE s.domain IN $domains AND coalesce(s.language, 'UAF') = 'UAF'
                RETURN s.name AS name, s.domain AS domain
                ORDER BY s.domain, s.name
                """,
                domains=list(IN_SCOPE_DOMAINS),
            )
            return [r.data() for r in result]
    finally:
        driver.close()


def parse_relationship_constants(java_file: Path) -> list[str]:
    text = java_file.read_text(encoding="utf-8")
    seen: list[str] = []
    for match in REL_CONSTANT_RE.finditer(text):
        value = match.group(1)
        if value not in seen:
            seen.append(value)
    return seen


def to_property_iri(rel_type: str) -> str:
    # PERFORMS -> performs ; INFORMATION_FLOW -> informationFlow
    parts = rel_type.lower().split("_")
    head, *tail = parts
    return head + "".join(p.capitalize() for p in tail)


def render_turtle(stereotypes: list[dict], rel_types: list[str]) -> str:
    today = date.today().isoformat()
    by_domain: dict[str, list[str]] = {d: [] for d in IN_SCOPE_DOMAINS}
    for row in stereotypes:
        by_domain[row["domain"]].append(row["name"])

    lines: list[str] = []
    lines.append("# UAF Minimum Viable Ontology (MVO)")
    lines.append("# Stage 2 — Strategic + Operational + Resource domains only.")
    lines.append("# AUTO-GENERATED by ontology/codegen/generate_mvo.py — do not hand-edit.")
    lines.append("# Source of truth: UAFStereotypeRegistry.java + UAFRelationshipDTO.java")
    lines.append("")
    lines.append("@prefix owl:     <http://www.w3.org/2002/07/owl#> .")
    lines.append("@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .")
    lines.append("@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .")
    lines.append("@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .")
    lines.append("@prefix dcterms: <http://purl.org/dc/terms/> .")
    lines.append(f"@prefix uaf:     <{UAF_NS}> .")
    lines.append(f"@prefix uafprop: <{UAF_PROP_NS}> .")
    lines.append("")
    lines.append(f"<{ONTOLOGY_IRI}> a owl:Ontology ;")
    lines.append('    rdfs:label "UAF MVO (Strategic + Operational + Resource)" ;')
    lines.append('    rdfs:comment "Minimum Viable Ontology covering UAF 1.2 stereotypes in the Strategic, Operational and Resource domains, generated from UAFStereotypeRegistry." ;')
    lines.append('    owl:versionInfo "0.1.0" ;')
    lines.append(f'    dcterms:created "{today}"^^xsd:date .')
    lines.append("")

    # Domain abstract superclasses
    lines.append("# --- Domain abstract superclasses --------------------------------------------")
    lines.append("")
    for domain, super_name in DOMAIN_TO_SUPERCLASS.items():
        lines.append(f"uaf:{super_name} a owl:Class ;")
        lines.append(f'    rdfs:label "{super_name}" ;')
        lines.append(f'    rdfs:comment "Abstract superclass for UAF {domain.lower()} domain elements." ;')
        lines.append(f'    uafprop:domain "{domain}" .')
        lines.append("")

    # Stereotype classes
    lines.append("# --- Stereotype classes ------------------------------------------------------")
    lines.append("")
    for domain in IN_SCOPE_DOMAINS:
        super_name = DOMAIN_TO_SUPERCLASS[domain]
        lines.append(f"# {domain}")
        for stereotype in sorted(by_domain[domain]):
            lines.append(f"uaf:{stereotype} a owl:Class ;")
            lines.append(f'    rdfs:label "{stereotype}" ;')
            lines.append(f"    rdfs:subClassOf uaf:{super_name} ;")
            lines.append(f'    uafprop:domain "{domain}" ;')
            lines.append(f"    rdfs:isDefinedBy <{ONTOLOGY_IRI}> .")
            lines.append("")

    # Object properties
    lines.append("# --- Object properties (UAF relationship types) ------------------------------")
    lines.append("")
    for rel in rel_types:
        prop_iri = to_property_iri(rel)
        lines.append(f"uaf:{prop_iri} a owl:ObjectProperty ;")
        lines.append(f'    rdfs:label "{rel}" ;')
        lines.append(f'    uafprop:neo4jType "{rel}" ;')
        lines.append(f"    rdfs:isDefinedBy <{ONTOLOGY_IRI}> .")
        lines.append("")

    # Domain annotation property declaration
    lines.append("# --- Annotation properties ---------------------------------------------------")
    lines.append("")
    lines.append("uafprop:domain a owl:AnnotationProperty ;")
    lines.append('    rdfs:label "uaf domain" .')
    lines.append("")
    lines.append("uafprop:neo4jType a owl:AnnotationProperty ;")
    lines.append('    rdfs:label "neo4j relationship type" .')
    lines.append("")

    return "\n".join(lines)


def render_mappings(stereotypes: list[dict], rel_types: list[str]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by ontology/codegen/generate_mvo.py — do not hand-edit.")
    lines.append("// n10s URI <-> Neo4j label/relationship mappings for the MVO.")
    lines.append("// Sourced from ontology/n10s-init.cypher.")
    lines.append("")
    lines.append("// --- Class mappings (URI -> Neo4j label) ---")
    for row in sorted(stereotypes, key=lambda r: (r["domain"], r["name"])):
        name = row["name"]
        lines.append(
            f'CALL n10s.mapping.add("{UAF_NS}{name}","{name}");'
        )
    lines.append("")
    lines.append("// --- Object property mappings (URI -> Neo4j rel type) ---")
    for rel in rel_types:
        prop_iri = to_property_iri(rel)
        lines.append(
            f'CALL n10s.mapping.add("{UAF_NS}{prop_iri}","{rel}");'
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    uri = os.getenv("NEO4J_URI", "bolt://localhost:7687")
    user = os.getenv("NEO4J_USERNAME", "neo4j")
    password = os.getenv("NEO4J_PASSWORD", "Password123")
    database = os.getenv("NEO4J_DATABASE", "neo4j")

    print(f"Querying {uri} for in-scope stereotypes...", file=sys.stderr)
    stereotypes = fetch_stereotypes(uri, user, password, database)
    if not stereotypes:
        print(
            "ERROR: no in-scope :Stereotype nodes found. Did you run init_uaf_graph.cypher?",
            file=sys.stderr,
        )
        return 1

    print(f"Parsing relationship constants from {RELATIONSHIP_DTO.name}...", file=sys.stderr)
    rel_types = parse_relationship_constants(RELATIONSHIP_DTO)
    if not rel_types:
        print("ERROR: no REL_* constants parsed from UAFRelationshipDTO.java", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    TTL_OUT.write_text(render_turtle(stereotypes, rel_types), encoding="utf-8")
    MAPPINGS_OUT.write_text(render_mappings(stereotypes, rel_types), encoding="utf-8")

    print(f"Wrote {TTL_OUT.relative_to(REPO_ROOT)} "
          f"({len(stereotypes)} classes, {len(rel_types)} object properties)",
          file=sys.stderr)
    print(f"Wrote {MAPPINGS_OUT.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
